name: Build

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y xvfb keepass2
    - run: dotnet build -c Release src
    - name: plgx create
      run: |
        cp -rv assets output
        cat src/*.cs | grep ^using | sort -u > output/Plugin.cs
        cat src/*.cs | grep ^.assembly: >> output/Plugin.cs
        cat src/*.cs | grep -Ev '^(using|.assembly:)' >> output/Plugin.cs
        xvfb-run keepass2 -plgx-create $PWD/output
    - uses: actions/upload-artifact@v4
      with:
        path: output.plgx
